testcmenv/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#loginpage'
  resources :fusions
  get "/fusionstest", to: "fusions#test"
  resources :users
  resources :visitors
  get "/secure", to: "sessions#loginpage"
  post "/login", to: "sessions#login"
  delete "/logout", to: "sessions#logout"
  get "/dashboard", to: "sessions#index"
  post "/searchvisitor", to: "visitors#searchvisitor"
end

testcmenv/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

testcmenv/app/controllers/fusions_controller.rb
require 'net/http'

class FusionsController < ApplicationController
  layout "fusions"
  @refreshtime = 360
  @@logger = Logger.new('logfile.log')
  @@hostnames = ["dev01.vm.tm0.com",
    "app.dev01.vm.tm0.com",
    "app.dev01.vm.tm0.com/cgi-bin/admin/become.cgi",
    "app2.dev01.vm.tm0.com",
    "app2.dev01.vm.tm0.com/cgi-bin/admin/become.cgi",
    "ebm.dev01.vm.tm0.com",
    "ttb.dev01.vm.tm0.com/browse",
    "tt.dev01.vm.tm0.com/ttview",
    "webmail.dev01.vm.tm0.com",
    "qa26.vm.tm0.com",
    "app.qa26.vm.tm0.com",
    "app.qa26.vm.tm0.com/cgi-bin/admin/become.cgi",
    "ebm.qa26.vm.tm0.com",
    "webmail.qa26.vm.tm0.com",
    "ttb.qa26.vm.tm0.com/browse",
    "tt.qa26.vm.tm0.com/ttview",
    ]
  @@stagehostnames = [
    "app.staging.cheetahmail.com/cgi-bin/admin/become.cgi",
    "app.staging.cheetahmail.com",
    "ebm.staging.cheetahmail.com",
    "ttb.staging.cheetahmail.com/browse",
    "tt01.staging.cheetahmail.com/ttview",
    "webmail.staging.cheetahmail.com"
  ]
  
  @@proxyservers = [
    "proxy.staging.cheetahmail.com",
    "443"
  ]

  @@testhostnames = [
    "app.dev01.vm.tm0.com",
    "qa26.vm.tm0.com"
  ]

  def index
    @res = []
    curl3(@@hostnames, nil, @res)
    respond_to do |format|
      format.html
    end
    @res2 = []
    curl3(@@stagehostnames, @@proxyservers, @res2)
    respond_to do |format|
      format.html
    end
    @nexturl = "http://localhost:3000/fusions"
  end

  def test
    @res = []
    curl3(@@testhostnames, nil, @res)
    respond_to do |format|
      format.html
    end
  end

  private

    def curl3(hostnames, proxyservers=nil, res=nil)
      res.clear
      hostnames.each do |hostname|
        begin
          sleep 5
          uri = URI.parse("https://"+hostname)
          if proxyservers.nil?
            http = Net::HTTP.new(uri.host, uri.port)
          else
            http = Net::HTTP.new(uri.host, uri.port, @@proxyservers[0], @@proxyservers[1])
          end
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          request = Net::HTTP::Get.new(uri.request_uri)
          response = http.request(request)
          content = response.body.gsub("\n", "").squeeze()
          if response.code == 200
            res.push "200:#{hostname}"
            @@logger.debug("success:#{hostname}:#{content}");
          else
            res.push "#{response.code}:#{hostname}"
            @@logger.debug("#{response.code}:#{hostname}:#{content}");
          end
          puts response.body
        rescue Exception => e
          res.push "999:#{hostname}"
          @@logger.debug("error:#{hostname}:#{e.message}");
        end
      end
    end

    def curl2(hostnames, proxyservers=nil)
      hostnames.each do |hostname|
        begin
          sleep 5
          uri = URI.parse("https://"+hostname)
          if proxyservers.nil?
            http = Net::HTTP.new(uri.host, uri.port)
          else
            http = Net::HTTP.new(uri.host, uri.port, @@proxyservers[0], @@proxyservers[1])
          end
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          request = Net::HTTP::Get.new(uri.request_uri)
          response = http.request(request)
          content = response.body.gsub("\n", "").squeeze()
          if response.code == 200
            @@logger.debug("success:#{hostname}:#{content}");
          else
            @@logger.debug("#{response.code}:#{hostname}:#{content}");
          end
          puts response.body
        rescue Exception => e
          @@logger.debug("error:#{hostname}:#{e.message}");
        end
      end
    end

    def curl(hostname)
      sleep 5
      begin
        uri = URI.parse("https://"+hostname)
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request = Net::HTTP::Get.new(uri.request_uri)
        response = http.request(request)
        content = response.body.gsub("\n", "").squeeze()
        if response.code == 200
          @@logger.debug("success:#{hostname}:#{content}");
        else
          @@logger.debug("#{response.code}:#{hostname}:#{content}");
        end
        puts response.body
      rescue Exception => e
        @@logger.debug("error:#{hostname}:#{e.message}");
      end
    end
    
end

testcmenv/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  layout "sessions/layouts/sessions"
  include SessionsHelper
  before_action :require_login, except: [:loginpage, :login]
 
  def index
    respond_to do |format|
      format.html
    end
  end

  def loginpage
    if logged_in?
      redirect_to :action => "index"
    else
      respond_to do |format|
        format.html
      end
    end
  end

  def login
    puts "Email: #{params[:session][:email]}"
    puts "Password: #{params[:session][:password]}"
    if params[:session][:email] == "aaa@aaa.com"      
      flash[:error] = 'Invalid email/password combination' # Not quite right!
      logout
    else
      log_in(params[:session])
      redirect_to :action => "index"
    end
    
  end

  def logout
    log_out
    redirect_to "/secure"
  end

private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/secure"
    end
  end

end

testcmenv/app/controllers/users_controller.rb
class UsersController < SessionsController  
  include SessionsHelper
 
  def index
  end

end

testcmenv/app/controllers/visitors_controller.rb
class VisitorsController < SessionsController
  
  #http://railscasts.com/episodes/240-search-sort-paginate-with-ajax

  def index
    
  end

  def searchvisitor
    
  end

end

testcmenv/app/helpers/application_helper.rb
module ApplicationHelper
end

testcmenv/app/helpers/fusions_helper.rb
module FusionsHelper
  def meta_refresh_tag nexturl
    return "<meta http-equiv=\"refresh\" content=\"900; URL=#{nexturl}\" >".html_safe
  end
end

testcmenv/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(p)
    session[:userid] = p[:email];
    session[:password] = p[:password];
    session[:logindt] = Time.new.inspect;
    puts "Session User Id: #{session[:userid]}"
    puts "Session Password: #{session[:password]}"
    puts "Session Date Time #{session[:logindt]}"
    p[:email] == "admin@aaa.com" ? session[:isadmin] = 1 : session[:isadmin] = 0
    puts "Session Administrator #{session[:isadmin]}"
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= session[:userid]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    clearusersession
    @current_user = nil
  end

  def clearusersession
    session[:userid] = nil
    session[:password] = nil
    session[:logindt] = nil
    session[:isadmin] = nil
  end

end

testcmenv/app/views/fusions/index.html.erb
<div><b>TIME</b></div>
<div><%=Time.new.inspect%></div>
<br/><br/>

<div><b>VM DEV01 & QA26</b></div>
<%  @res.each do |res| %>
<div><%=res%></div>
<%  end %>
<br/><br/>

<div><b>Staging</b></div>
<%  @res2.each do |res2| %>
<div><%=res2%></div>
<%  end %>

<br/><br/>
<div><b>HTTP Code:Information</b></div>
<div>200:OK.</div>
<div>301:Moved Permanently</div>
<div>302:Found.Moved Temporarily.An HTTP response with this status code will additionally provide a URL in the location header field.</div>
<div>401:Unauthorized.</div>
<div>999:Fusion Error.</div>

testcmenv/app/views/fusions/test.html.erb
<div><%=Time.new.inspect%></div>
<%  @res.each do |res| %>
<div><%=res%></div>
<%  end %>

testcmenv/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testcmenv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

testcmenv/app/views/layouts/fusions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fusions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= meta_refresh_tag @nexturl %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

testcmenv/app/views/visitors/index.html.erb
    <%= form_for(:visitor, url: searchvisitor_path, method: "post") do |f| %>
      <%= f.label :first_name %>: <%= f.text_field :first_name %>  <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>

testcmenv/app/views/visitors/layouts/visitors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fusions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= form_for(:session, url: logout_path, method: "delete") do |f| %>
      <%= f.submit "Log Out", class: "btn btn-primary" %>
    <% end %>
  </body>
</html>